# Generated by Django 3.1.7 on 2021-04-03 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(max_length=4)),
                ('arm', models.CharField(max_length=1)),
                ('no_of_students', models.IntegerField()),
            ],
            options={
                'verbose_name_plural': 'Classes',
            },
        ),
        migrations.CreateModel(
            name='Teachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('title', models.CharField(max_length=4)),
                ('subject', models.CharField(max_length=64)),
                ('admin_role', models.CharField(max_length=64)),
                ('staffID', models.CharField(max_length=11)),
            ],
            options={
                'verbose_name_plural': 'Teachers',
            },
        ),
        migrations.CreateModel(
            name='Students',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adm_number', models.CharField(max_length=4, unique=True)),
                ('surname', models.CharField(max_length=20)),
                ('othernames', models.CharField(max_length=40)),
                ('DOB', models.DateField()),
                ('cl_teacher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom', to='schedule.classes')),
                ('presentclass', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='students', to='schedule.classes')),
            ],
            options={
                'verbose_name_plural': 'Students',
            },
        ),
        migrations.CreateModel(
            name='ClassTeachers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schedule.teachers')),
            ],
            options={
                'verbose_name_plural': 'ClassTeachers',
            },
        ),
        migrations.AddField(
            model_name='classes',
            name='classteacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='classteacher', to='schedule.classteachers'),
        ),
    ]
