# Generated by Django 3.1.7 on 2021-04-03 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0002_auto_20210403_1754'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='classteacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='_class', to='schedule.classteachers'),
        ),
        migrations.AlterField(
            model_name='students',
            name='cl_teacher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='students', to='schedule.classes'),
        ),
        migrations.AlterField(
            model_name='students',
            name='presentclass',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student', to='schedule.classes'),
        ),
    ]
