# Generated by Django 3.1.7 on 2021-04-04 08:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0003_auto_20210403_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classteachers',
            name='name',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.teachers'),
        ),
    ]
