# Generated by Django 3.1.7 on 2021-04-05 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0004_auto_20210404_0831'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='classteacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, to='schedule.classteachers'),
        ),
    ]
