# Generated by Django 3.1.7 on 2021-04-05 08:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0005_auto_20210405_0721'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='classteacher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='schedule.classteachers'),
        ),
    ]
