# Generated by Django 3.1.7 on 2021-04-06 12:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('schedule', '0007_auto_20210406_0411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='classteacher',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='schedule.classteachers'),
        ),
    ]
